# Generated by Django 3.0.2 on 2020-04-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('NO2', models.IntegerField(blank=True, null=True)),
                ('PM10', models.IntegerField(blank=True, null=True)),
                ('PM25', models.IntegerField(blank=True, null=True)),
                ('O3', models.IntegerField(blank=True, null=True)),
                ('SO2', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='products.Country', verbose_name='countries')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
