# Generated by Django 3.0.2 on 2020-04-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_city_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='NO2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='O3',
        ),
        migrations.RemoveField(
            model_name='city',
            name='PM10',
        ),
        migrations.RemoveField(
            model_name='city',
            name='PM25',
        ),
        migrations.RemoveField(
            model_name='city',
            name='SO2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='date',
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NO2', models.IntegerField(blank=True, null=True)),
                ('PM10', models.IntegerField(blank=True, null=True)),
                ('PM25', models.IntegerField(blank=True, null=True)),
                ('O3', models.IntegerField(blank=True, null=True)),
                ('SO2', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='products.City', verbose_name='cities')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
