# Generated by Django 3.0.2 on 2020-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200419_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
