# Generated by Django 3.0.2 on 2020-04-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200419_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitudeDelta',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitudeDelta',
        ),
    ]
