# Generated by Django 3.0.2 on 2020-04-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200425_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercities',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.City', verbose_name='cities'),
        ),
        migrations.AlterField(
            model_name='usercities',
            name='user',
            field=models.IntegerField(auto_created=True),
            preserve_default=False,
        ),
    ]
