# Generated by Django 3.0.2 on 2020-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200425_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercities',
            name='user',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
