# Generated by Django 3.0.2 on 2020-04-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200425_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='products.Country', verbose_name='countries'),
        ),
    ]
