# Generated by Django 3.0.2 on 2020-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200426_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercities',
            name='notifications',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
